name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.4'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Launch4j
        run: |
          ./launch4j/launch4j.exe ${{ github.workspace }}/launch4j-config.xml

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/outputs/FTLautosave.exe # Adjust this path based on your build output
          asset_name: FTLautosave.exe
          asset_content_type: application/octet-stream
